// Generated by CoffeeScript 1.3.3
(function() {
  var SGF_SIGNATURE, UDPShoutor, dgram;

  dgram = require('dgram');

  SGF_SIGNATURE = 6258000;

  UDPShoutor = (function() {

    function UDPShoutor(communicationPort, channelId, onMsgCallback) {
      if (!(communicationPort > 1024 && channelId >= 0 && (onMsgCallback != null))) {
        throw new Error("invalid argumens");
      }
      this.communicationPort = communicationPort;
      this.channelId = channelId;
      this.client = dgram.createSocket("udp4");
      this.client.on('message', onMsgCallback);
      this.bufSignature = new Buffer(11);
      this.bufSignature.fill(0);
      this.bufSignature.writeUInt32BE(SGF_SIGNATURE, 0);
      this.bufSignature.writeUInt32BE(channelId, 4);
    }

    UDPShoutor.prototype.sendMessage = function(buf) {
      if (!(Buffer.isBuffer(buf) && buf.length > 0)) {
        return;
      }
      buf = Buffer.concat([this.bufSignature, buf]);
      return this.client.send(buf, 0, buf.length, this.communicationPort, "localhost");
    };

    return UDPShoutor;

  })();

  module.exports = UDPShoutor;

}).call(this);
