// Generated by CoffeeScript 1.3.3
(function() {
  var UDPShoutor, channelId, onMessage, shoutor;

  UDPShoutor = require("../util/udpshoutor");

  channelId = (4 * Math.random() >> 0) + 1;

  onMessage = function(msg, rinfo) {
    return console.log("[client(" + process.pid + ")] msg:" + (msg.toString()) + ", from:" + rinfo.address + ":" + rinfo.port);
  };

  shoutor = new UDPShoutor(9999, channelId, onMessage);

  setInterval(function() {
    var message;
    message = new Buffer("channelId:" + channelId + " pid:" + process.pid + ", time:" + (Date.now()));
    return shoutor.sendMessage(message);
  }, 1000);

}).call(this);
