// Generated by CoffeeScript 1.6.3
(function() {
  var PORT, UDPShoutor, channelId, onMessage, shoutor;

  UDPShoutor = require("../udpcomm").UDPShoutor;

  PORT = 9999;

  channelId = 5;

  onMessage = function(msg, rinfo) {
    return console.log("[client(" + process.pid + ")] msg:" + (msg.toString()) + ", from:" + rinfo.address + ":" + rinfo.port);
  };

  shoutor = new UDPShoutor(PORT, channelId, onMessage);

  setInterval(function() {
    var message;
    message = new Buffer("channelId:" + channelId + " pid:" + process.pid + ", time:" + (Date.now()));
    return shoutor.sendMessage(message);
  }, 1000);

}).call(this);
